User preferences database migrations & entities
Nuvalence/ds4g-user-api pull request #11
Opened 2022-04-15 19:13 UTC by gmisail

This pull requests adds migration changesets for the user preference (`user_preference`) and language (`language_table`) tables. I also added two new JPA entities (`UserPreferenceEntity` & `LanguageEntity` respectively) so that we can interface with these new tables. Note that this pull request satisfies tickets WP-87 and WP-88 since they were closely related.

2022-04-15 19:46 UTC, JayStGelais requested changes

2022-04-15 19:46 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/ds4g/user/api/service/entity/LanguageEntity.java
> +    @Column(name = "complainant", nullable = false, unique = false)
From a common component perspective, I don't think we can codify the breakdown of applications (referred to as user types here, but the limitation will be application driven as that is the unit that we apply localization requirements to) for workers protection as the form by which we configure language preference. We probably need to map languages allowed by application, where the list of applications are also confugrable.

2022-04-20 13:07 UTC, JayStGelais approved these changes

2022-04-26 15:06 UTC, Mark-The-Dev approved these changes
With the imports fixed and it's building correctly, this is approved

2022-04-26 15:15 UTC, merged